### PR TITLE
Correctly refer to the UI class

### PR DESCRIPTION
**Pull request by DanToml**
closes https://github.com/CocoaPods/cocoapods-acknowledgements/issues/31

### CODE REVIEW

**Comment by orta** [comment]
👍

**Comment by DanToml** [comment]
@orta Build is failing due to active support ruby versions. 😞. How do we wanna fix this for tests?

**Comment by orta** [comment]
Same as CocoaPods I'm afraid, cap it at under 5 - https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec#L43-L44

**Comment by DanToml** [comment]
@orta 👍 updated

**Comment by orta** [comment]
rock

**Pull request merged**
