### PR TITLE
Add the homepage to the metadata

### PR DESCRIPTION
**Pull request by orta**
When I started wrapping up CPDAcknowledgements - I noticed that this was missing from the metadata

### CODE REVIEW

**Comment by segiddins** [comment]
Changelog and test?

**Comment by segiddins** [comment]
Pring

**Comment by orta** [comment]
Sorry, struggling to find out of work hours to write code

**Comment by segiddins** [comment]
No worries, I got this working locally, I'll ship the 1.1.1 update in a couple of minutes!

**Pull request merged**
